### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by Swedz** [EXSolo/challonge-java#4]
How do I add this to my maven pom.xml?

I tried:

    <dependency>
      <groupId>com.exsoloscript.challonge</groupId>
      <artifactId>challonge-java</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>

However this gives a few errors:
![capture](https://cloud.githubusercontent.com/assets/6707125/19991059/c2aa7378-a208-11e6-98a2-ffa4229cd5b6.PNG)

**Comment by EXSolo** [comment]
For now, this project is not available at the central repository. If you want to use my library, you need to clone this repository and install it to your local repository (simply run `mvn install` once). After that you should be able to use it on your local device.

**Comment by Swedz** [comment]
This project needs a maven link since I can't even just copy and paste the src into my src, it just gives loads of errors, and once I fixed them all, it didn't even work.

**Comment by EXSolo** [comment]
This project does not use any external repositories. All dependencies can be found at maven central. You don't need to copy the source files to your folder. Simply clone or download this project to a folder of your choice and run `mvn install` once. This will automatically copy the built jar to your local repository, which can be found at `~/.m2/repository/com/exsoloscript/challonge/challonge-java`. Once you did that you can add the dependency to your project.

**Comment by EXSolo** [comment]
I deployed this artifact to the central repository. You should be able to use it without having to compile it yourself.
